---
# once all workers joined, run with --tags delete_token to kill the join token on master

- hosts: k8sall
  vars:
    kubeadm_version:       "1.16.2-00"
    containerdio_version: "1.2.10-3"
    docker_ce_cli_version: "5:18.09.9~3-0~debian-buster"
    docker_ce_version:     "5:18.09.9~3-0~debian-buster"
    install_dashboard: yes
    dashboard_version:     "v2.0.0-beta5"
  roles:
    - pi-k8s
      
