---

- name: 'check for cni'
  when: inventory_hostname in groups['k8smasters']
  register: cni_check_result
  shell: "kubectl get pods -n kube-system | grep 'weave'"
  changed_when: false
  failed_when: cni_check_result.rc != 0 and cni_check_result.rc != 1
  ignore_errors: true
  tags: cni,weave

##############################
### 
### needs kernel version >= 4.19.81-v7l+ ...
### see https://github.com/weaveworks/weave/issues/3717#issuecomment-552221620
###
##############################

- name: 'install weave'
  when: inventory_hostname in groups['k8smasters'] and cni_check_result.rc != 0
  any_errors_fatal: yes
  # see latest info at https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#tabs-pod-install-10
  shell:
    cmd: "kubectl apply -f \"https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')\""
  args:
    warn: no
  tags: cni,weave

