---

- name: 'check for cni'
  when: inventory_hostname in groups['k8smasters']
  register: cni_check_result
  shell: "kubectl get pods -n kube-system | grep 'calico'"
  changed_when: false
  failed_when: cni_check_result.rc != 0 and cni_check_result.rc != 1
  ignore_errors: true
  tags: cni,calico

- name: 'check for explicit pod_network_cidr'
  fail:
    msg: "pod_network_cidr must be defined for calico install"
  when: pod_network_cidr is not defined
  tags: cni,calico

- name: 'process pod_network_cidr'
  set_fact:
    escaped_pod_network_cidr: '{{ pod_network_cidr | replace("/","\/") }}'
  tags: cni,calico
    
- name: 'install calico'
  when: inventory_hostname in groups['k8smasters'] and calico_version is defined and cni_check_result.rc != 0
  any_errors_fatal: yes
  # see latest version in https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#tabs-pod-install-0
  shell:
    cmd: 'curl -fsSL https://docs.projectcalico.org/{{ calico_version }}/manifests/calico-etcd.yaml | sed "s/192\.168\.0\.0\/16/{{ escaped_pod_network_cidr }}/g" | kubectl apply -f -'
    #cmd: 'curl -fsSL https://docs.projectcalico.org/{{ calico_version }}/manifests/calico-etcd.yaml | kubectl apply -f -'
  args:
   warn: no
  tags: cni,calico

