- name: 'check for nginx ingress'
  when: inventory_hostname in groups['k8smasters']
  register: ingress_check_result
  shell: "kubectl get pods -n ingress-nginx | grep 'nginx-ingress-controller'"
  changed_when: false
  failed_when: ingress_check_result.rc != 0 and ingress_check_result.rc != 1
  ignore_errors: true
  tags: ingress,nginx

- name: 'install nginx ingress'
  when: inventory_hostname in groups['k8smasters'] and nginx_ingress_version is defined and ingress_check_result.rc != 0
  any_errors_fatal: yes
  shell:
    cmd: |
        curl -fsSL https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-{{ nginx_ingress_version }}/deploy/static/provider/baremetal/deploy.yaml |
        sed -E "s;^( *)(targetPort: *http *$);\1\2\n\1nodePort: {{ ingress_http_nodeport | default('31000') }} ;" |
        sed -E "s;^( *)(targetPort: *https);\1\2\n\1nodePort: {{ ingress_https_nodeport | default('31001') }} ;" |
        kubectl apply -f -
  args:
    warn: no
  tags: ingress,nginx
