---

######### see https://www.domoticz.com/forum/viewtopic.php?t=28797

- name: "install open-iscsi & initramfs-tools"
  become: yes
  apt:
    force_apt_get: yes # there's no need to use aptitude
    name: ['open-iscsi','initramfs-tools']
    state: present
    install_recommends: no
  tags: iscsiroot,netroot

- name: "disable ib_iser" # <- was causing error during boot on pi4b
  become: yes
  register: iscsi_iser
  lineinfile:
    path: "/lib/modules-load.d/open-iscsi.conf"
    regexp: '^(ib_iser)$'
    line: '#\1'
    backrefs: yes
  tags: iscsiroot,netroot
  when: is_raspbian

- name: "enable iscsi service"
  become: yes
  systemd:
    name: iscsi.service
    enabled: yes
    state: "{{'restarted' if iscsi_iser.changed else 'started'}}"
  tags: iscsiroot,netroot

- name: "check for existing iscsi root"
  set_fact:
    iscsi_root_found: yes
  no_log: true
  with_items: "{{ ansible_mounts }}"
  when: "item.mount=='/' and 'ext4' in item.fstype and '/dev/sd' in item.device"
  tags: iscsiroot,netroot

- name: "mount iscsi lun"
  register: iscsimount
  become: yes
  open_iscsi:
    auto_node_startup: yes
    discover: yes
    login: yes
    portal: "{{ iscsi_root_ip }}"
    port: "{{ iscsi_root_port | default('3260') }}"
    target: '{{ iscsi_root_iqn | replace("{{ inventory_hostname }}",inventory_hostname) }}'
    node_user: '{{ iscsi_root_username | default("") | replace("{{ inventory_hostname }}",inventory_hostname) | regex_replace("[^a-zA-Z0-9]","") }}'
    node_pass: '{{ iscsi_root_password | default("") }}'
  when: iscsi_root_found is not defined
  tags: iscsiroot,netroot

- name: "find iscsi device"
  set_fact:
    iscsi_device: "{{ iscsimount.devicenodes[0] }}"
  when: iscsi_root_found is not defined
  tags: iscsiroot,netroot

- name: "make ext4 filesystem on iscsi device"
  become: yes
  register: mkfs_result
  filesystem:
    fstype: ext4
    dev: "{{ iscsi_device }}"
    resizefs: yes
  when: iscsi_root_found is not defined
  tags: iscsiroot,netroot

- name: "Get iscsi lun uuid"
  become: yes
  command: "lsblk --noheadings --output uuid {{ iscsi_device }}"
  register: iscsi_uuid
  changed_when: false
  when: iscsi_root_found is not defined
  tags: iscsiroot,netroot

- name: "Get initiator name"
  become: yes
  register: iscsi_initiator
  shell: "cat /etc/iscsi/initiatorname.iscsi | grep -v '^##' | tail -1 | cut -d'=' -f2"
  changed_when: false
  when: iscsi_root_found is not defined
  tags: iscsiroot,netroot

## thanks: https://docs.ansible.com/ansible/latest/user_guide/playbooks_blocks.html
- block:
    - name: "create temp iscsi mountpoint"
      become: yes
      tempfile:
        state: directory
        suffix: "iscsitemp"
        path: "{{ ansible_env.HOME }}"
      register: iscsitemp

    - name: "mount iscsi root source"
      become: yes
      mount:
        path: "{{ iscsitemp.path }}"
        src: "{{ iscsi_device }}"
        fstype: "ext4"
        opts: defaults
        state: mounted
      register: iscsimount

# rc=24 occurs when a file or directory "vanished" before rsync got a chance to
# copy it - happens with e.g. log/lock files
    - name: "rsync copy root partition"
      become: yes
      register: rsync
      command: "rsync -xaq --delete --exclude {{ iscsitemp.path }} / {{ iscsitemp.path }}"
      failed_when: rsync.rc != 0 and rsync.rc != 24

#%%% continue here
#%%% this is where it fails on ubuntu
#%%% possibly see https://www.hiroom2.com/2018/05/05/ubuntu-1804-open-iscsi-en/#sec-3
    - name: "comment out sd card root mount"
      become: yes
      lineinfile:
        path: "{{ iscsitemp.path}}/etc/fstab"
        regexp: "{{ '^((LABEL=writable  / )$)' if (is_ubuntu) else '^((PARTUUID=[0-9a-zA-Z-]*  / .*)$)' }}"
        line: '#\1'
        backrefs: yes

    - name: "add iscsi root mount"
      become: yes
      lineinfile:
        path: "{{ iscsitemp.path }}/etc/fstab"
        regexp: "^UUID={{ iscsi_uuid.stdout }} */ *ext4 *{{ '_netdev' if (is_ubuntu) else 'defaults' }} *{{ '0' if (is_ubuntu) else '1' }} *{{ '0' if (is_ubuntu) else '1' }}$"
        line: "UUID={{ iscsi_uuid.stdout }}       /       ext4    {{ '_netdev' if (is_ubuntu) else 'defaults' }}        {{ '0' if (is_ubuntu) else '1' }}       {{ '0' if (is_ubuntu) else '1' }}"

  always:
    - name: "unmount iscsi root source in copy"
      become: yes
      lineinfile:
        path: "{{ iscsitemp.path }}/etc/fstab"
        regexp: "^{{ iscsi_device }} *{{ iscsitemp.path }} *ext4.*$"
        state: absent
      when: iscsimount is defined and not iscsimount.failed

    - name: "unmount iscsi root source local"
      become: yes
      mount:
        path: "{{ iscsitemp.path }}"
        state: absent
      when: iscsimount is defined and not iscsimount.failed

    - name: "remove temp iscsi mountpoint"
      become: yes
      file:
        path: "{{ iscsitemp.path }}"
        state: absent
      when: iscsitemp.path is defined
  when: iscsi_root_found is not defined
  tags: iscsiroot,netroot

- name: 'copy cmdline.txt to cmdline.txt.before_iscsi'
  become: yes
  copy:
    src: "{{ cmdline_txt_path }}"
    dest: "{{ cmdline_txt_path }}.before_iscsi"
    remote_src: yes
    force: no
  when: iscsi_root_found is not defined
  tags: iscsiroot,netroot

- name: 'copy cmdline.txt to cmdline.txt.iscsi'
  become: yes
  copy:
    src: "{{ cmdline_txt_path }}"
    dest: "{{ cmdline_txt_path }}.iscsi"
    remote_src: yes
    force: yes
  when: iscsi_root_found is not defined
  tags: iscsiroot,netroot

- name: 'copy config.txt to config.txt.before_iscsi'
  become: yes
  copy:
    src: "{{ config_txt_path }}"
    dest: "{{ config_txt_path }}.before_iscsi"
    remote_src: yes
    force: no
  when: iscsi_root_found is not defined
  tags: iscsiroot,netroot

- name: 'copy config.txt to config.txt.iscsi'
  become: yes
  copy:
    src: "{{ config_txt_path }}"
    dest: "{{ config_txt_path }}.iscsi"
    remote_src: yes
    force: yes
  when: iscsi_root_found is not defined
  tags: iscsiroot,netroot

- name: 'make initramfs'
  become: yes
  register: initramfs
  shell:
    cmd: 'update-initramfs -k {{ ansible_kernel }} -c'
    creates: '/boot/initrd.img-{{ ansible_kernel }}'
  when: iscsi_root_found is not defined
  tags: iscsiroot,netroot

- name: 'add initramfs to config.txt.iscsi'
  become: yes
  lineinfile:
    path: "{{ config_txt_path }}.iscsi"
    line: 'initramfs initrd.img-{{ ansible_kernel }} followkernel'
  when: iscsi_root_found is not defined
  tags: iscsiroot,netroot

- name: "remove sd root partition from cmdline.txt.iscsi"
  become: yes
  register: sd_cmd
  lineinfile:
    path: "{{ cmdline_txt_path }}.iscsi"
    regexp: '^(.*)(root=PARTUUID=[0-9a-zA-Z-]* *)(.*$)'
    line: '\1\3'
    backrefs: yes   
  when: iscsi_root_found is not defined
  tags: iscsiroot,netroot

- name: "create root cmdline.txt.iscsi entry"
  set_fact:
    iscsi_cmdline: 'ISCSI_INITIATOR={{ iscsi_initiator.stdout }} ISCSI_TARGET_NAME={{ iscsi_root_iqn | replace("{{ inventory_hostname }}",inventory_hostname) }} ISCSI_TARGET_IP={{ iscsi_root_ip }} ISCSI_TARGET_PORT={{ iscsi_root_port | default("3260") }} ISCSI_TARGET_GROUP=1 rw root=UUID={{ iscsi_uuid.stdout }}'
  when: iscsi_root_found is not defined
  tags: iscsiroot,netroot

- name: 'add iscsi root to cmdline.txt.iscsi'
  become: yes
  register: iscsi_cmd
  lineinfile:
    path: "{{ cmdline_txt_path }}.iscsi"
    regexp: '^(((?! {{ iscsi_cmdline }}).)*$)'
    line: '\1 {{ iscsi_cmdline }}'
    backrefs: yes
  when: iscsi_root_found is not defined
  tags: iscsiroot,netroot

- name: 'add fstype to cmdline.txt.iscsi'
  become: yes
  register: type_cmd
  lineinfile:
    path: "{{ cmdline_txt_path }}.iscsi"
    regexp: '^(((?! rootfstype=ext4).)*$)'
    line: '\1 rootfstype=ext4'
    backrefs: yes
  when: iscsi_root_found is not defined
  tags: iscsiroot,netroot

- name: 'copy cmdline.txt.iscsi to cmdline.txt'
  become: yes
  register: cmdlinecopy
  copy:
    src: "{{ cmdline_txt_path }}.iscsi"
    dest: "{{ cmdline_txt_path }}"
    remote_src: yes
    force: yes
  tags: iscsiroot,netroot
  when: iscsi_root_dontinstall is not defined

- name: 'copy config.txt.iscsi to config.txt'
  become: yes
  register: configcopy
  copy:
    src: "{{ config_txt_path }}.iscsi"
    dest: "{{ config_txt_path }}"
    remote_src: yes
    force: yes
  tags: iscsiroot,netroot
  when: iscsi_root_dontinstall is not defined

- name: 'reboot after setting up iscsi root'
  become: yes
  reboot:
  when: iscsi_root_dontinstall is not defined and ((iscsi_root_found is not defined and not rsync.failed) or cmdlinecopy.changed or configcopy.changed)
  tags: iscsiroot,netroot

