- import_tasks iscsi_initiatorname.yml

- name: 'install tgt'
  become: yes
  apt:
    force_apt_get: yes # there's no need to use aptitude
    name: 'tgt'
    state: present
    update_cache: yes
    cache_valid_time: 3600 # Only run "update_cache=yes" if the last one is more than 3600 seconds ago
  tags: iscsi_server
