---

- name: "get kernel commit details"
  run_once: yes
  set_fact:
    kernel_commits: "{{ lookup('url', 'https://api.github.com/repos/Hexxeh/rpi-firmware/commits') }}"

# thanks: https://www.tailored.cloud/devops/advanced-list-operations-ansible/
#         https://stackoverflow.com/a/40659528/2738122
- name: "find matching shas"
  run_once: yes
  set_fact:
    kernel_shas: "{% for commit_data in kernel_commits %}\
                    {% if commit_data.sha.startswith(kernel_version) or commit_data.commit.message.startswith('kernel: Bump to '+kernel_version)%}\
                      {{ commit_data.sha }}\
                    {% endif %}\
                  {% endfor %}"
    failed_when: kernel_shas | count > 1

- name: "get new kernel version"
  set_fact:
    new_kernel_version: ????

- name: "do rpi-update"
  become: yes
  register: rpi_update
  shell:
    cmd: "rpi-update SKIP_WARNING=1 RPI_REBOOT=0 {{ kernel_shas[0] }}"
  changed_when: ??? rpi-update returns 0 if ok, but what does it create for sure?

- name: 'make initramfs'
  become: yes
  register: initramfs
  shell:
    cmd: 'update-initramfs -k {{ new_kernel_version }} -c'
    creates: '/boot/initrd.img-{{ new_kernel_version }}'
  when: iscsi_root_found is not defined

- name: 'add initramfs to config.txt'
  become: yes
  lineinfile:
    path: /boot/config.txt
    regex: '(?<!#)\s*initramfs/s+initrd.img-{{ ansible_kernel }}/s+followkernel'  %%% <--- test this
    line: 'initramfs initrd.img-{{ new_kernel_version }} followkernel'
    state: present
    create: no

- name: 'add initramfs to config.txt.iscsi' # created by this role's iscsiroot tasks
  become: yes
  lineinfile:
    path: /boot/config.txt.iscsi
    regex: '(?<!#)\s*initramfs/s+initrd.img-{{ ansible_kernel }}/s+followkernel'  %%% <--- test this
    line: 'initramfs initrd.img-{{ new_kernel_version }} followkernel'
    state: present
    create: no
  fail_when: no

- name: "record kernel updated"
  set_fact:
    kernel_version_changed: yes
    when: rpi_update.changed or initramfs.changed or config_kernel.changed
