---

- name: 'get token'
  when: inventory_hostname == target_masters[0]
  register: token_result
  shell: "kubeadm token list | grep 'kubeadm init' | cut -f1 -d' '"
  tags: delete_token

- name: 'get token sha'
  when: inventory_hostname == target_masters[0]
  register: token_sha_result
  shell: "openssl x509 -pubkey -in /etc/kubernetes/pki/ca.crt | openssl rsa -pubin -outform der 2>/dev/null | openssl dgst -sha256 -hex | sed 's/^.* //'"

- name: 'check for joined node'
  when: inventory_hostname in target_workers
  register: node_check_result
  shell: "kubectl get nodes | grep {{ inventory_hostname }}"
  changed_when: false
  failed_when: node_check_result.rc != 0 and node_check_result.rc != 1
  ignore_errors: true
  delegate_to: "{{ target_masters[0] }}"

- name: 'check for token if join needed'
  when: inventory_hostname in target_workers and node_check_result.rc != 0 and (hostvars[target_masters[0]]['token_result']['rc'] != 0 or hostvars[target_masters[0]]['token_result']['stdout'] == "") and (hostvars[target_masters[0]]['token_sha_result']['rc'] != 0 or hostvars[target_masters[0]]['token_sha_result']['stdout'] == "")
  fail:
    msg: "Worker join required, but token information not found - was master included in hosts?"

- name: 'join cluster'
  when: inventory_hostname in target_workers and node_check_result.rc != 0
  register: node_join_result
  become: yes
  command: "kubeadm join {{ hostvars[target_masters[0]]['ansible_default_ipv4']['address']}}:6443 --token {{ hostvars[target_masters[0]]['token_result']['stdout'] }} --discovery-token-ca-cert-hash sha256:{{ hostvars[target_masters[0]]['token_sha_result']['stdout'] }}"

- name: 'pause 2 mins for kubernetes workers to begin start up'
  run_once: yes
  when: inventory_hostname in target_workers and node_join_result is defined and node_join_result.changed
  wait_for:
    timeout: 120
  delegate_to: localhost

- name: 'wait up to another 2 mins for all nodes to come up'
  run_once: yes
  when: inventory_hostname in target_workers
  command: 'kubectl wait --for=condition=ready --timeout=120s nodes --all'
  delegate_to: "{{ target_masters[0] }}"

- name: 'label node with memory'
  when: inventory_hostname in target_workers
  command: 'kubectl label --overwrite node {{ inventory_hostname }} kolossi/pi-mem-gb={{ "8" if ansible_memtotal_mb |int > 7000 else "4" if ansible_memtotal_mb | int > 3000 else "2" if ansible_memtotal_mb | int > 1500 else "1" }}'
  delegate_to: "{{ target_masters[0] }}"
  
