---

- name: 'get token'
  when: inventory_hostname == groups['k8smasters'][0]
  register: token_result
  shell: "kubeadm token list | grep 'kubeadm init' | cut -f1 -d' '"
  tags: delete_token

- name: 'get token sha'
  when: inventory_hostname == groups['k8smasters'][0]
  register: token_sha_result
  shell: "openssl x509 -pubkey -in /etc/kubernetes/pki/ca.crt | openssl rsa -pubin -outform der 2>/dev/null | openssl dgst -sha256 -hex | sed 's/^.* //'"

- name: 'check for joined node'
  when: inventory_hostname in groups['k8sworkers']
  register: node_check_result
  shell: "kubectl get nodes | grep {{ inventory_hostname }}"
  changed_when: false
  failed_when: node_check_result.rc != 0 and node_check_result.rc != 1
  ignore_errors: true
  delegate_to: "{{ groups['k8smasters'][0] }}"

- name: 'check for token if join needed'
  when: inventory_hostname in groups['k8sworkers'] and node_check_result.rc != 0 and (hostvars[groups['k8smasters'][0]]['token_result']['rc'] != 0 or hostvars[groups['k8smasters'][0]]['token_result']['stdout'] == "") and (hostvars[groups['k8smasters'][0]]['token_sha_result']['rc'] != 0 or hostvars[groups['k8smasters'][0]]['token_sha_result']['stdout'] == "")
  fail:
    msg: "Worker join required, but token information not found - was master included in hosts?"

- name: 'join cluster'
  when: inventory_hostname in groups['k8sworkers'] and node_check_result.rc != 0
  become: yes
  command: "kubeadm join {{ hostvars[groups['k8smasters'][0]]['ansible_default_ipv4']['address']}}:6443 --token {{ hostvars[groups['k8smasters'][0]]['token_result']['stdout'] }} --discovery-token-ca-cert-hash sha256:{{ hostvars[groups['k8smasters'][0]]['token_sha_result']['stdout'] }}"

- name: 'wait for all nodes to come up'
  when: inventory_hostname == groups['k8smasters'][0]
  command: 'kubectl wait --for=condition=ready nodes --all'

