---

- import_tasks: pi_setup.yml
  tags: pi_setup

- import_tasks: upgrade.yml
  tags: upgrade

- import_tasks: docker.yml
  tags: docker

- import_tasks: kubernetes.yml
  tags: kubernetes,k8s

- import_tasks: kubernetes_master.yml
  tags: kubernetes,k8s,kubernetes_master,k8s_master

- include_tasks: "cni_{{ 'flannel' if (flannel_version is defined) else 'weave' }}.yml"
  tags: cni,flannel,weave

- import_tasks: kubernetes_worker.yml
  tags: kubernetes,k8s,kubernetes_worker,k8s_worker

- import_tasks: dashboard.yml
  tags: dashboard

- import_tasks: dashboard.yml
  tags: delete_token, never # <- never means this will only run if delete_token explictly given on the commandline


## https://github.com/kairen/kubeadm-ansible

