---

- import_tasks: process_facts.yml
  tags: always

- include_tasks: "pi_setup_{{ os_name }}.yml"
  tags: pi_setup

- import_tasks: pi_setup.yml
  tags: pi_setup

- include_tasks: "nfsroot.yml"
  tags: netroot, nfsroot
  when: nfs_root_source is defined

- include_tasks: "iscsiroot.yml"
  tags: netroot, iscsiroot
  when: iscsi_root_iqn is defined

- import_tasks: upgrade.yml
  tags: upgrade

- import_tasks: docker.yml
  tags: docker

- import_tasks: kubernetes.yml
  tags: kubernetes

- import_tasks: kubernetes_master.yml
  tags: kubernetes,kubernetes_master

- include_tasks: "cni_{{ 'flannel' if (flannel_version is defined) else 'weave' }}.yml"
  tags: cni,flannel,weave

- import_tasks: kubernetes_worker.yml
  tags: kubernetes,kubernetes_worker

- include_tasks: "dashboard.yml"
  tags: dashboard
  when: install_dashboard|default(False) and dashboard_version is defined

- import_tasks: delete_token.yml
  tags: delete_token, never # <- never means this will only run if delete_token explictly given on the commandline


## https://github.com/kairen/kubeadm-ansible

