---

- name: "process vars"
  set_fact:
    #params
    filesystem_device:     '{{ filesystem_device }}'
    filesystem_force_make: '{{ filesystem_force_make | default("False") }}' 

- name: "make ext4 filesystem on iscsi device '{{ filesystem_device }}'"
  become: yes
  register: mkfs_result
  filesystem:
    fstype: ext4
    dev: "{{ filesystem_device }}"
    force: "{{ filesystem_force_make }}" 

# do not combine with creation above, filesystem module does not support
# create and resize, it will only do resize if both options given
- name: "expand ext4 filesystem to whole iscsi device '{{ filesystem_device }}'"
  become: yes
  register: mkfs_resize_result
  filesystem:
    fstype: ext4
    dev: "{{ filesystem_device }}"
    resizefs: yes
  when: mkfs_result.changed
