---

- name: 'update hostname'
  when: inventory_hostname != ansible_hostname
  register: hostname_result
  become: yes
  lineinfile:
    path: /etc/hostname
    regexp: '^{{ ansible_hostname }}'
    line: "{{ inventory_hostname }}"
    owner: root
    group: root
    mode: '0644'

- name: 'add cgroup enable cpuset to cmdline.txt'
  register: config_cgroup_enable_cpuset_result
  become: yes
  lineinfile:
    path: "{{ cmdline_txt_path }}"
    regexp: '^(((?! cgroup_enable=cpuset).)*$)'
    line: '\1 cgroup_enable=cpuset'
    backrefs: yes

- name: 'add cgroup memory to cmdline.txt'
  register: config_cgroup_memory_result
  become: yes
  lineinfile:
    path: "{{ cmdline_txt_path }}"
    regexp: '^(((?! cgroup_memory=1).)*$)'
    line: '\1 cgroup_memory=1'
    backrefs: yes

- name: 'add cgroup enable memory to cmdline.txt'
  register: config_cgroup_enable_memory_result
  become: yes
  lineinfile:
    path: "{{ cmdline_txt_path }}"
    regexp: '^(((?! cgroup_enable=memory).)*$)'
    line: '\1 cgroup_enable=memory'
    backrefs: yes

- name: 'store /tmp in ram'
  become: yes
  register: tmp_ram_result
  when: (tmp_ram | default(false))
  mount:
    src: tmpfs
    path: /tmp
    fstype: tmpfs
    opts: defaults,noatime,size=200m
    state: present
    
- name: 'store /var/log in ram'
  become: yes
  when: (log_ram | default(false))
  register: log_ram_result
  mount:
    src: tmpfs
    path: /var/log
    fstype: tmpfs
    opts: defaults,noatime,size=64m
    state: present

- name: 'setup nfs data mount'
  when: nfs_data_mountpoint is defined and nfs_data_source is defined
  become: yes
  mount:
    src: "{{ nfs_data_source }}"
    path: "{{ nfs_data_mountpoint }}"
    fstype: nfs
    opts: defaults
    state: mounted

- name: 'reboot after initial setup'
  when: |
    (bootwait_result is defined and bootwait_result.changed)
      or (bootwait_w_result is defined and bootwait_w_result.changed)
      or (bootwait_z_result is defined and bootwait_z_result.changed)
      or (hostname_result is defined and hostname_result.changed)
      or (hosts_result is defined and hosts_result.changed)
      or config_cgroup_enable_cpuset_result.changed
      or config_cgroup_memory_result.changed
      or config_cgroup_enable_memory_result.changed
      or (tmp_ram_result is defined and tmp_ram_result.changed)
      or (log_ram_result is defined and log_ram_result.changed)
      or (config_disable_wifi_result is defined and config_disable_wifi_result.changed)
      or (config_disable_bt_dt_result is defined and config_disable_bt_dt_result.changed)
      or (config_disable_bt_modem_result is defined and config_disable_bt_modem_result.changed)
      or (kernel_lib_extract is defined and kernel_lib_extract.changed)
      or (kernel_boot is defined and kernel_boot_extract.changed)
      or (config_kernel is defined and config_kernel.changed)
      or (ntp_server_result is defined and ntp_server_result.changed)
  become: yes
  reboot:
