---

- name: "is ubuntu"
  set_fact:
    is_ubuntu: "{{ True if (ansible_distribution=='Ubuntu') else False }}"

- name: "is raspbian"
  set_fact:
    is_raspbian: "{{ False if (is_ubuntu) else True }}"

- name: "os name"
  set_fact:
    os_name: "{{ 'ubuntu' if (is_ubuntu) else 'raspbian' }}"

- name: "get boot dir path"
  set_fact:
    boot_path: "{{ '/boot/firmware' if (is_ubuntu) else '/boot' }}"

- name: "get config.txt path"
  set_fact:
    config_txt_path: "{{ boot_path }}/config.txt"

- name: 'get cmdline filename'
  shell: "grep ^[^#]*cmdline {{ config_txt_path }} | cut -d= -f2"
  register: cmdline_txt_name
  changed_when: false
  failed_when: false

- name: "get cmdline.txt path"
  set_fact:
    cmdline_txt_path: "{{ boot_path }}/{{ cmdline_txt_name.stdout|default('cmdline.txt',true) }}"

- name: "get cni name"
  set_fact:
    cni_name: "{{ 'calico' if (calico_version is defined) else 'flannel' if (flannel_version is defined) else 'weave' }}"

- name: "get target masters"
  set_fact:
    target_masters: "{{ groups['k8smasters'] | intersect(play_hosts) }}"

- name: "get target workers"
  set_fact:
    target_workers: "{{ groups['k8sworkers'] | intersect(play_hosts) }}"

- name: "fail if multiple tmp options given"
  fail:
    msg: "use tmp_mem OR tmp_workdir not both"
  when: tmp_mem|default(False) and tmp_workdir|default(False)

- name: "fail if multiple log options given"
  fail:
    msg: "use log_mem OR log_workdir not both"
  when: log_mem|default(False) and log_workdir|default(False)
