---

- name: 'Upgrade all packages to the latest version'
  become: yes
  register: upgrade_result
  apt:
    force_apt_get: yes # there's no need to use aptitude
    update_cache: yes
    cache_valid_time: 3600 # Only run "update_cache=yes" if the last one is more than 3600 seconds ago
    name: "*"
    state: latest

- name: 'Remove dependencies that are no longer required'
  become: yes
  register: autoremove_result
  apt:
    force_apt_get: yes # there's no need to use aptitude
    autoremove: yes

- import_tasks: 'kernel_version.yml'
  when: kernel_version is defined
  tags: kernelversion

- debug:
    msg:
      - "%upgrade_result.changed%: {{ upgrade_result.changed }}"
      - "%autoremove_result.changed%: {{ autoremove_result.changed }}"
      - "%kernel_version_changed | default(False)%: {{ kernel_version_changed | default(False) }}"
      - "%kernel_version_changed%: {{ kernel_version_changed }}"
  tags: kernelversion

- name: 'reboot after updates'
  when: upgrade_result.changed or autoremove_result.changed or (kernel_version_changed | default(False))
  become: yes
  reboot:
  tags: kernelversion

