#! /bin/bash

### BEGIN INIT INFO
# Provides:          pi-leds
# Required-Start:    uuidd
# Required-Stop:     uuidd 
# Default-Start:     1 2 3 4 5
# Default-Stop:      0 6
# Short-Description: Change raspberry pi leds
# Description:       Use green on/red off for running and
#                    green off/red flashing for shutting down
### END INIT INFO

set -e

name=`basename $0`
stdout_log="/var/log/pi-leds.log"

echo "$0 $*" >> $stdout_log
echo "-----" >> $stdout_log
case "$1" in
    start|restart)
    led0command='default-on'
    led1command='none'
    echo "  led0=${led0command}" >> $stdout_log
    echo "  led1=${led1command}" >> $stdout_log
    echo ${led0command} >> /sys/class/leds/led0/trigger
    echo ${led1command} >> /sys/class/leds/led1/trigger
    ;;
    stop)
    led0command='none'
    led1command='heartbeat'
    echo "  led0=${led0command}" >> $stdout_log
    echo "  led1=${led1command}" >> $stdout_log
    echo ${led0command} >> /sys/class/leds/led0/trigger
    echo ${led1command} >> /sys/class/leds/led1/trigger
    ;;
    status)
    # do nothing
    ;;
    *)
    echo "Usage: $0 {start|stop|restart|status}"
    echo "  exit 1" >> $stdout_log
    exit 1
    ;;
esac

echo "  exit 0" >> $stdout_log
exit 0
